export const Colors = {
  primary: '#FC3C62',
  mediumPrimary: '#fc5576',
  lightPrimary: '#FED5DD',
  white: '#ffffff',
  black: '#2b2b2b',
  grey: '#939393',
  extraDarkGrey: '#333333',
  lightGrey: '#B4B4B4',
  extraLightGrey: '#949494',
  regularGrey: '#E7E4E4',
  blue: '#0C569B',
  red: '#E82E20',
  transparent: 'transparent',
  lightYellow: '#F4F2E3',
  yellow: '#FFE8C8',
  green: '#074E17',
  lightGreen: '#C6EFCF',
  extraGreen: '#1E996D',
  red: '#F80000',
  ParrotColor: '#52A90E',
  darkRed: '#E32B2B',
  lightPink: '#FFD8DF',
  extraLightPink: '#FDE7EB',
  transparentBlack: '#00000080',
  regularPink: '#F8F1F1',
  borderColor: '#8D8D8D',
  darkGrey: '#5A5A5A',
  pending: 'rgb(234 179 8)',
  pendingBg: 'rgb(254 252 232)',
  success: 'rgb(22 163 74)',
  successBg: 'rgb(240 253 244)',
  disable: '#555555',
  disable1: '#999999',
  bord: '#E4E4E4',
  bg1: '#F5F5F5',
  info: '#0d47a1',
};
export const StaffColors = [
  '#cdb4db',
  '#ffc8dd',
  '#ffafcc',
  '#bde0fe',
  '#1d3557',
  '#ffdfba',
  '#390099',
  '#9e0059',
  '#ff0054',
  '#c7f9cc',
  '#6a0572',
  '#f6c7ab',
  '#f0a500',
  '#ff8c00',
  '#ff5733',
  '#ff6f61',
  '#87e752',
  '#17ffc4',
  '#ff4500',
  '#ff0000',
  '#ff1493',
  '#5cf64a',
  '#ff6eb4',
  '#6b0f1a',
  '#f4d58d',
  '#006ba6',
  '#0582ca',
  '#4aff05',
  '#ff0789',
  '#f6d258',
  '#f615ba',
  '#01d669',
  '#1593f6',
  '#850a0a',
  '#ff6347',
  '#ff4500',
  '#6a8532',
  '#ff00ff',
  '#ff007f',
  '#ff1493',
  '#ff69b4',
  '#87a330',
  '#ff6f61',
  '#ff8c00',
  '#ff4500',
  '#ff0000',
  '#eecf6d',
  '#ff8c00',
  '#644536',
  '#b2675e',
  '#c4a381',
  '#bbd686',
  '#eef1bd',
  '#3c1518',
  '#69140e',
  '#a44200',
  '#d58936',
  '#8ecae6',
  '#219ebc',
  '#023047',
  '#ffb703',
];
export const DefaultImage =
  'https://bookingapp-aws-s3-images-bucket.s3.us-west-1.amazonaws.com/blank_profile_b72ab56cfa.png';
export const calendarTheme = {
  backgroundColor: '#ffffff',
  calendarBackground: '#ffffff',
  textSectionTitleColor: '#000000',
  textSectionTitleDisabledColor: '#000000',
  selectedDayBackgroundColor: Colors.primary,
  selectedDayTextColor: '#ffffff',
  todayTextColor: Colors.primary,
  dayTextColor: '#2d4150',
  textDisabledColor: '#d9e1e8',
  dotColor: Colors.primary,
  selectedDotColor: '#ffffff',
  arrowColor: 'black',
  disabledArrowColor: '#d9e1e8',
  monthTextColor: 'black',
  indicatorColor: 'blue',
  textDayFontWeight: '300',
  textMonthFontWeight: 'bold',
  textDayHeaderFontWeight: '300',
  textDayFontSize: 15,
  textMonthFontSize: 15,
  textDayHeaderFontSize: 15,
};
export const Fonts = {
  Primary40Bold: {
    color: Colors.primary,
    fontSize: 40,
    fontFamily: 'Bold',
  },
  Primary22Bold: {
    color: Colors.primary,
    fontSize: 22,
    fontFamily: 'Bold',
  },
  Primary20Bold: {
    color: Colors.primary,
    fontSize: 20,
    fontFamily: 'Bold',
  },

  Primary18Bold: {
    color: Colors.primary,
    fontSize: 18,
    fontFamily: 'Bold',
  },
  Primary16Bold: {
    color: Colors.primary,
    fontSize: 16,
    fontFamily: 'Bold',
  },

  Primary15Bold: {
    color: Colors.primary,
    fontSize: 15,
    fontFamily: 'Bold',
  },
  Primary22Medium: {
    color: Colors.primary,
    fontSize: 22,
    fontFamily: 'Medium',
  },
  Primary18Medium: {
    color: Colors.primary,
    fontSize: 18,
    fontFamily: 'Medium',
  },
  Primary16Medium: {
    color: Colors.primary,
    fontSize: 16,
    fontFamily: 'Medium',
  },
  Primary15Medium: {
    color: Colors.primary,
    fontSize: 15,
    fontFamily: 'Medium',
  },

  Primary14Medium: {
    color: Colors.primary,
    fontSize: 14,
    fontFamily: 'Medium',
  },
  Primary14Regular: {
    color: Colors.primary,
    fontSize: 14,
    fontFamily: 'Regular',
  },
  Divider: {
    height: 1,
    backgroundColor: Colors.bord,
  },
  Black28Bold: {
    color: Colors.black,
    fontSize: 28,
    fontFamily: 'Bold',
  },
  Black24Bold: {
    color: Colors.black,
    fontSize: 24,
    fontFamily: 'Bold',
  },
  Black22Bold: {
    color: Colors.black,
    fontSize: 22,
    fontFamily: 'Bold',
  },
  Black18Bold: {
    color: Colors.black,
    fontSize: 18,
    fontFamily: 'Bold',
  },
  Black16Bold: {
    color: Colors.black,
    fontSize: 16,
    fontFamily: 'Bold',
  },
  Black18Medium: {
    color: Colors.black,
    fontSize: 18,
    fontFamily: 'Medium',
  },
  Black16Medium: {
    color: Colors.black,
    fontSize: 16,
    fontFamily: 'Medium',
  },

  Black15Medium: {
    color: Colors.black,
    fontSize: 15,
    fontFamily: 'Medium',
  },
  Black14Medium: {
    color: Colors.black,
    fontSize: 14,
    fontFamily: 'Medium',
  },
  Black16Regular: {
    color: Colors.black,
    fontSize: 16,
    fontFamily: 'Regular',
  },
  Black14Regular: {
    color: Colors.black,
    fontSize: 14,
    fontFamily: 'Regular',
  },
  Black14: {
    color: Colors.black,
    fontSize: 14,
  },

  White16Bold: {
    color: Colors.white,
    fontSize: 16,
    fontFamily: 'Bold',
  },
  White14Bold: {
    color: Colors.white,
    fontSize: 14,
    fontFamily: 'Bold',
  },

  Yellow20Bold: {
    color: Colors.yellow,
    fontSize: 20,
    fontFamily: 'Bold',
  },

  White20Bold: {
    color: Colors.white,
    fontSize: 20,
    fontFamily: 'Bold',
  },
  White18Bold: {
    color: Colors.white,
    fontSize: 18,
    fontFamily: 'Bold',
  },

  Green14Bold: {
    color: Colors.green,
    fontSize: 14,
    fontFamily: 'Bold',
  },
  Grey15Bold: {
    color: Colors.grey,
    fontSize: 15,
    fontFamily: 'Bold',
  },
  Grey14Bold: {
    color: Colors.grey,
    fontSize: 14,
    fontFamily: 'Bold',
  },
  ExtraLightGrey14Bold: {
    color: Colors.extraLightGrey,
    fontSize: 14,
    fontFamily: 'Bold',
  },
  ExtraLightGrey14SemiBold: {
    color: Colors.extraLightGrey,
    fontSize: 14,
    fontFamily: 'SemiBold',
  },
  white14SemiBold: {
    color: Colors.white,
    fontSize: 14,
    fontFamily: 'SemiBold',
  },
  White18SemiBold: {
    color: Colors.white,
    fontSize: 18,
    fontFamily: 'SemiBold',
  },
  Grey14Medium: {
    color: Colors.grey,
    fontSize: 14,
    fontFamily: 'Medium',
  },
  ExtraLightGrey18Medium: {
    color: Colors.extraLightGrey,
    fontSize: 18,
    fontFamily: 'Medium',
  },
  Grey12Medium: {
    color: Colors.grey,
    fontSize: 12,
    fontFamily: 'Medium',
  },

  White16Medium: {
    color: Colors.white,
    fontSize: 16,
    fontFamily: 'Medium',
  },

  ExtraLightGrey16Medium: {
    color: Colors.extraLightGrey,
    fontSize: 16,
    fontFamily: 'Medium',
  },
  ExtraLightGrey14Medium: {
    color: Colors.extraLightGrey,
    fontSize: 14,
    fontFamily: 'Medium',
  },

  Grey16Medium: {
    color: Colors.grey,
    fontSize: 16,
    fontFamily: 'Medium',
  },
  Red16Medium: {
    color: Colors.red,
    fontSize: 16,
    fontFamily: 'Medium',
  },

  White14Medium: {
    color: Colors.white,
    fontSize: 14,
    fontFamily: 'Medium',
  },

  Grey14Regular: {
    color: Colors.grey,
    fontSize: 14,
    fontFamily: 'Regular',
  },
};

export const Default = {
  shadow: {
    shadowColor: Colors.black,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 3,
  },

  shadowPrimary: {
    shadowColor: Colors.primary,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 3,
  },
  fixPadding: 10,
};
export default { Colors, Fonts, Default };
