export const DATA = [
  {
    id: '11',
    image: require('@assets/images/hair1.png'),
    name: 'The Big Tease Salons 11',
    location: '1901 Thornridge Cir. Shiloh,Hawaii 81063 ',
    star: require('@assets/images/star5.png'),
    selected: false,
    services: [],
  },
  {
    id: '12',
    image: require('@assets/images/hair2.png'),
    name: 'Straight Razors',
    location: '1901 Thornridge Cir. Shiloh,Hawaii 81063 ',
    star: require('@assets/images/star3.png'),
    selected: false,
    services: [],
  },
  {
    id: '13',
    image: require('@assets/images/hair3.png'),
    name: 'Backyard Barbers',
    location: '1901 Thornridge Cir. Shiloh,Hawaii 81063 ',
    star: require('@assets/images/star4.png'),
    selected: true,
    services: [],
  },
  {
    id: '14',
    image: require('@assets/images/hair4.png'),
    name: 'Salon Zeppelin',
    location: '1901 Thornridge Cir. Shiloh,Hawaii 81063 ',
    star: require('@assets/images/star3.png'),
    selected: false,
    services: [],
  },
  {
    id: '15',
    image: require('@assets/images/hair5.png'),
    name: 'Brooklyn Barbers',
    location: '1901 Thornridge Cir. Shiloh,Hawaii 81063 ',
    star: require('@assets/images/star5.png'),
    selected: false,
    services: [],
  },
  {
    id: '16',
    image: require('@assets/images/hair6.png'),
    name: 'Barber Republic',
    location: '1901 Thornridge Cir. Shiloh,Hawaii 81063 ',
    star: require('@assets/images/star1.png'),
    selected: true,
    services: [],
  },
  {
    id: '17',
    image: require('@assets/images/hair7.png'),
    name: 'Hair salons',
    location: '1901 Thornridge Cir. Shiloh,Hawaii 81063 ',
    star: require('@assets/images/star4.png'),
    selected: false,
    services: [],
  },
  {
    id: '18',
    image: require('@assets/images/hair8.png'),
    name: 'Nail salons',
    location: '1901 Thornridge Cir. Shiloh,Hawaii 81063 ',
    location: '3517 W. Gray St. Utica,Pennsylvania 57867',
    star: require('@assets/images/star1.png'),
    selected: false,
    services: [],
  },
  {
    id: '19',
    image: require('@assets/images/hair9.png'),
    name: 'Makeup',
    location: '1901 Thornridge Cir. Shiloh,Hawaii 81063 ',
    star: require('@assets/images/star3.png'),
    selected: false,
    services: [],
  },
  {
    id: '20',
    image: require('@assets/images/hair10.png'),
    name: 'Skin care',
    location: '1901 Thornridge Cir. Shiloh,Hawaii 81063 ',
    star: require('@assets/images/star4.png'),
    selected: false,
    services: [],
  },
];

export const ourSpecialistsData = [
  {
    id: '2',
    image: require('@assets/images/pic2.png'),
    name: 'Shawn',
    status: 'nail artiest',
  },
  {
    id: '3',
    image: require('@assets/images/pic3.png'),
    name: 'Mitchell',
    status: 'manger',
  },
  {
    id: '4',
    image: require('@assets/images/pic4.png'),
    name: 'Kari',
    status: 'hair stylistt',
  },
  {
    id: '5',
    image: require('@assets/images/pic5.png'),
    name: 'Shawn',
    status: 'nail artiest',
  },
  {
    id: '6',
    image: require('@assets/images/pic6.png'),
    name: 'Mitchell',
    status: 'manger',
  },
  {
    id: '7',
    image: require('@assets/images/pic4.png'),
    name: 'Kari',
    status: 'hair stylistt',
  },
];

export const PhotoData = [
  {
    key: '1',
    image: require('@assets/images/photo1.png'),
  },
  {
    key: '2',
    image: require('@assets/images/photo2.png'),
  },
  {
    key: '3',
    image: require('@assets/images/photo3.png'),
  },
  {
    key: '4',
    image: require('@assets/images/photo4.png'),
  },
  {
    key: '5',
    image: require('@assets/images/photo5.png'),
  },
  {
    key: '6',
    image: require('@assets/images/photo6.png'),
  },
  {
    key: '7',
    image: require('@assets/images/photo7.png'),
  },
];
